-- NUSA KASIR -- Fix missing online store tables
-- Migration 0004 references store_settings and online_products but
-- neither table was ever created. This migration creates them.

-- Store configuration table
CREATE TABLE IF NOT EXISTS store_settings (
  store_id      TEXT PRIMARY KEY,
  owner_user_id TEXT DEFAULT '',
  store_name    TEXT NOT NULL DEFAULT '',
  slug          TEXT UNIQUE,
  description   TEXT DEFAULT '',
  whatsapp      TEXT DEFAULT '',
  address       TEXT DEFAULT '',
  open_hours    TEXT DEFAULT '08:00 - 21:00',
  is_active     BOOLEAN DEFAULT FALSE,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Online product catalog (synced from app)
CREATE TABLE IF NOT EXISTS online_products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id      TEXT NOT NULL REFERENCES store_settings(store_id) ON DELETE CASCADE,
  product_id    INTEGER NOT NULL,
  name          TEXT NOT NULL DEFAULT '',
  category      TEXT DEFAULT 'Lainnya',
  price         INTEGER DEFAULT 0,
  stock         INTEGER DEFAULT 0,
  image_url     TEXT DEFAULT '',
  description   TEXT DEFAULT '',
  is_published  BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_online_products_store ON online_products(store_id);
CREATE INDEX IF NOT EXISTS idx_online_products_published ON online_products(store_id, is_published);

-- RLS policies for store_settings
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read active stores" ON store_settings;
CREATE POLICY "Public can read active stores" ON store_settings
  FOR SELECT USING (is_active = TRUE);

-- RLS policies for online_products
ALTER TABLE online_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read published products" ON online_products;
CREATE POLICY "Public can read published products" ON online_products
  FOR SELECT USING (is_published = TRUE);

-- Allow service_role full access (needed by edge function)
ALTER TABLE store_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE online_products FORCE ROW LEVEL SECURITY;
